# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35ac1facf5fc0b2dadec51f9fd550e4f68895ce9ac0fa269c5fbd347649e04cb242c6745f3a559633daa6f84e34d038762ccaba388ea82c8e316410cf7127924

test:
  secret_key_base: 19cc4c66b3a84e7a5ea493c7cc1f90993ef6fc000c9946b637941c08f4660298a5a0ed6ee2bb333e27dd65b579762361e26db2e0e4db073180f946a5b0455d0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
